### ISSUE TITLE
maven repository

### ISSUE THREAD

**Issue by satybald** [zaneli/scalikejdbc-athena#1]
thanks for the library! what're your thoughts about publishing it to maven repository?

**Comment by zaneli** [comment]
I try to create sonatype project for publish it to maven central repository just now.
https://issues.sonatype.org/browse/OSSRH-38497

Please give me a second.

**Comment by zaneli** [comment]
@satybald 
I published it to the Maven Central Repository.
https://mvnrepository.com/artifact/com.zaneli/scalikejdbc-athena_2.12/0.1.0

Please try using it by all means!

**Comment by satybald** [comment]
awesome! thanks @zaneli

**Comment by satybald** [comment]
@zaneli I believe it's also worth mentioning this information in Readme file.

**Comment by zaneli** [comment]
I already added https://github.com/zaneli/scalikejdbc-athena/commit/d82c56c1d4d0507ce0e34fe63f15e802cd7962bd :)
