### ISSUE TITLE
Update JDBC version from 4.1 to 4.2

### ISSUE THREAD

**Issue by polyomino24** [zaneli/scalikejdbc-athena#14]
According to a Athena JDBC driver document, JDBC version 4.1 will be EOL.
https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html

**Comment by zaneli** [comment]
Actually, I believe that scalikejdbc-athena is not dependent on the version of the AthenaJDBC driver.
If we replace the JDBC driver we download with AthenaJDBC42-2.1.1.1001.jar and it works fine, I don't think we need to deal with scalikejdbc-athena.
In that case, I think we only need to change some of the README and CI settings.
However, it may be necessary to track changes in driver config options, as in this PR. #5

If you give me time to check, I will try to confirm that it works with AthenaJDBC42-2.1.1.1001.jar.
Or if you are capable of it, by all means let me know the results.

**Comment by polyomino24** [comment]
In my project, scalikejdbc-athena works with AthenaJDBC42-2.1.1.1001.jar
I just only use a following few config options though.
- driver
- url
- readOnly
- S3OutputLocation
- User
- Password
- Workgroup
- LogLevel

**Comment by zaneli** [comment]
I decided to add a note to the README. #15

However, I realized that we would need to fix to support [Athena JDBC 3.x driver](https://docs.aws.amazon.com/athena/latest/ug/jdbc-v3-driver.html) in the near future. 😓 
I will consider a separate response. #16

@polyomino24
Thank you! 🙏
