### ISSUE TITLE
Update AthenaJDBC version to 2.0.5

### ISSUE THREAD

**Issue by matsuiyuki** [zaneli/scalikejdbc-athena#2]
I want to use `AthenaJDBC41_2.0.5`. It is different from the configuration of `AthenaJDBC41-1.1.0`.  
[Migration from Previous Version of the JDBC Driver](https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html)

[Installation and Configuration Guide](https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.5/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf)

### New feature in Version 2.0.5 
[Amazon Athena releases an updated JDBC driver with improved performance when retrieving results](https://docs.aws.amazon.com/ja_jp/athena/latest/ug/connect-with-jdbc.html)

**Comment by zaneli** [comment]
I'll try it.
Please give me some time.

(or I hope someone else send a pull request for it...)

**Comment by matsuiyuki** [comment]
I'll do it.

**Comment by matsuiyuki** [comment]
Changes in versions 1.x to 2.x

### AthenaJDBC 1.x
Connection is always not readOnly.
```
val conn = DriverManager.getConnection(...)
conn.isReadOnly() // false
conn.setReadOnly(true)
conn.isReadOnly() // false
```

### AthenaJDBC 2.x
Connection defaults to readOnly.  
When creating a partition, etc., you need to change it
```
val conn = DriverManager.getConnection(...)
conn.isReadOnly() // true
conn.setReadOnly(false)
conn.isReadOnly() // false
```

### Counterplan
Add option `readOnly`, default: `true`.
