### ISSUE TITLE
DateTime conversion issue

### ISSUE THREAD

**Issue by alexduf** [zaneli/scalikejdbc-athena#8]
Hi!

Thanks for this project, it's quite convenient to be able to use bound variables with Athena.

I've noticed there's an issue when making use of sqlikejdbc's datetime conversion feature. I get a nullpointer [here](https://github.com/seratch/scalikejdbc/blob/master/scalikejdbc-core/src/main/scala/scalikejdbc/DBConnectionAttributesWiredResultSet.scala#L21) if I try to use `rs.zonedDateTime("myColumnName")`

This is because scalikejdbc sets the connectionAttributes to null [here](https://github.com/zaneli/scalikejdbc-athena/blob/a071ef0e67e394ff1ef315cc0929269f09adf505/src/main/scala/scalikejdbc/athena/AthenaSession.scala#L17)

I'm not sure if there's a work around or what's the best way to fix this.

**Comment by zaneli** [comment]
Thank you for reporting.
This is probably my lack of consideration.
I'll try to fix it.

I think `AthenaSession` probably need to set non-null `DBConnectionAttributes`.

**Comment by alexduf** [comment]
Sweet, thank you very much for taking the time to fix this @zaneli 🙏

**Comment by zaneli** [comment]
@alexduf 
Thank you too!
I have released the version `0.2.4` that has been fixed it.
https://mvnrepository.com/artifact/com.zaneli/scalikejdbc-athena_2.13/0.2.4
